- id: safe-commit
  name: safe-commit
  description: "Check that you are not committing to a protected branch"
  entry: safe-commit
  language: python
  language_version: python3
  require_serial: true
  types: [python]
